---
title: "Soybean emergence"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load libraries

```{r message=FALSE, warning=FALSE}
#Set work directory
setwd("/Users/ey239/Github/Mowtivation/rmarkdowns")

#Load packages 
library(tidyverse) ##install.packages("tidyverse")
library(knitr)
library(patchwork) ##install.packages("patchwork")
library(skimr)     ##install.packages("skimr")
library(readxl)
library(janitor) ##install.packages("janitor")

library(kableExtra) ##install.packages("kableExtra")
library(webshot) ##install.packages("webshot")
webshot::install_phantomjs()
library(viridis) ##install.packages("viridis")
library(lme4) ##install.packages("lme4")
library(lmerTest) ##install.packages("lmerTest")
library(emmeans) ##install.packages("emmeans")
library(rstatix) ##install.packages("rstatix")
#library(Matrix) ##install.packages("Matrix")
library(multcomp) ##install.packages("multcomp")
library(multcompView) ##install.packages("multcompView")
library(ggResidpanel) ##install.packages("ggResidpanel")
#library(car)
#library(TMB)  ##install.packages("TMB")
#library(glmmTMB)  ##install.packages("glmmTMB")
library(DHARMa)  ##install.packages("DHARMa")
library(performance) ##install.packages("performance")
#Load Functions
MeanPlusSe<-function(x) mean(x)+plotrix::std.error(x)

find_logw0=function(x){c=trunc(log(min(x[x>0],na.rm=T)))
d=exp(c)
return(d)}
```
<br>
# Load and clean data

##Load data

``` {r}
combined_raw <- read_excel("~/Github/Mowtivation/raw-data/All Treatments/combined_raw.xlsx")
kable(head(combined_raw))

```
## Clean data
```{r}
#Standardaze column names, convert to factors, check for outliers of variable**
clean_combined <- clean_names(combined_raw) |>  
  rename ('weed_control'= treatment) |> 
  mutate(across(c(weed_control, block, plot, location, year), as.factor)) #|> 
  #mutate(is_outlier = totwbm < (quantile(totwbm, 0.25) - 1.5 * IQR(totwbm)) |
                       #wbm > (quantile(totwbm, 0.75) + 1.5 * IQR(totwbm)))

#select and convert data for wbm analysis
bean_emergence_clean <-clean_combined |>              
  mutate(bean_emergence_two_meter = (bean_emergence * 2)) |> 
  mutate(bean_emergence_acre = (((bean_emergence/0.762) *10000)/2.471)) |> 
   mutate(bean_emergence_hectare = ((bean_emergence / 0.762) * 10000))

kable(head(bean_emergence_clean)) 
```

#Model testing

```{r}
emergence.lmer <- lmer(bean_emergence_hectare  ~ weed_control*location + (1|location:block) , data = bean_emergence_clean)

resid_panel(emergence.lmer)
simulateResiduals(emergence.lmer,plot = TRUE) # Residuals and normality look good
check_model(emergence.lmer)
```

##Joint test (anova)
```{r}

joint_tests(emmeans(emergence.lmer, ~ weed_control * location))
```

```{r}
options(contrasts = c("contr.sum", "contr.poly"))
emergence.anova <- anova(emergence.lmer, ddf = "Satterthwaite")
print(emergence.anova)
```
br>

## Tukey means comparisons
### Weed-control (significant)

```{r}
tukey_weed_control <- emmeans(emergence.lmer, pairwise ~ weed_control, adjust = "tukey")
tukey_weed_control

cld_weed_control_tukey <- cld(emmeans(emergence.lmer, ~ weed_control), adjust = "tukey", Letters = letters, sort = TRUE, reversed = TRUE)

cld_weed_control_tukey
```
<br>

### Location (Significant)
```{r}
tukey_location <- emmeans(emergence.lmer, list(pairwise ~ location), adjust = "tukey")
tukey_location

cld_location_tukey <- cld(emmeans(emergence.lmer, ~ location), adjust = "tukey", Letters = letters, sort = TRUE, reversed = TRUE)

cld_location_tukey
```

###weed_control:location (not significant)

```{r}
tukey_weed_control_location <- emmeans(emergence.lmer, list(pairwise ~ weed_control|location), adjust = "tukey")
tukey_weed_control_location

cld_weed_control_location_tukey <- cld(emmeans(emergence.lmer, ~ weed_control|location), adjust = "tukey", Letters = letters, sort = TRUE, reversed = TRUE)

cld_weed_control_location_tukey
```









#Figures
## Location (S)

```{r message=FALSE, warning=FALSE}
bean_emergence_clean |> 
  left_join(cld_location_tukey) |> 
  ggplot(aes(x = location, y = bean_emergence_acre, fill = location)) +
  stat_summary(geom = "bar", fun = "mean", width = 0.7) +
  stat_summary(geom = "errorbar", fun.data = "mean_se", width = 0.2) +
  stat_summary(geom="text", fun = "MeanPlusSe", aes(label= trimws(.group)),size=6.5,vjust=-0.5) +
  
  labs(
    x = "Location",
    y = expression("Soybean emergence" ~ (plants * "/" * a)),
    title = str_c("The influence of location on soybean emergence"),
    subtitle = expression(italic("P = 0.01"))) +
   scale_x_discrete(labels = c("Field O2 East ",
                              "Field O2 West",
                              "Field X")) +
  scale_y_continuous(labels = scales::label_comma(),expand = expansion(mult = c(0.05, 0.3))) +
  scale_fill_viridis(discrete = TRUE, option = "D", direction = -1, end = 0.9, begin = 0.1) +
   theme_bw() +
  theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 12)
  )
ggsave("bean_emergence_location_plantsAc.png", width = 8, height = 6, dpi = 300)
```
#### weed_control:location (not significant)

```{r message=FALSE, warning=FALSE}
bean_emergence_clean |> 
  left_join(cld_weed_control_location_tukey ) |> 
  ggplot(aes(x = factor(weed_control, levels = c("RNO", "RIM", "RIC", "TIM", "TIC")), y =  bean_emergence_hectare, fill = weed_control)) +
  facet_wrap( ~location, labeller = labeller(
    location = c("field O2 east" = "Field O2 East", "field O2 west" = "Field O2 West","field v" = "Field V" )))+
  stat_summary(geom = "bar", fun = "mean", width = 0.7) +
  stat_summary(geom = "errorbar", fun.data = "mean_se", width = 0.2) +
  #stat_summary(geom="text", fun = "MeanPlusSe", aes(label= trimws(.group)),size=6.5,vjust=-0.5) +
  labs(
    x = "",
    y = expression(paste("Soybean emergence (", plants~ha^{-1}, ")")),

    #title = str_c("The influence of interrow weed control on soybean yield"),
    subtitle = expression(italic("Not significant"))) +
  
  scale_x_discrete(labels = c("Rolled,\nno additional\nweed control",
                              "Rolled,\ninterrow\nmowing",
                              "Rolled,\nhigh-residue\ncultivation",
                              "Tilled,\ninterrow\nmowing",
                          "Tilled,\nstandard\ncultivation")) +
  scale_y_continuous(
  labels = scales::label_comma(),
  expand = expansion(mult = c(0.05, 0.3))
) +
  scale_fill_viridis(discrete = TRUE, option = "D", direction = -1, end = 0.9, begin = 0.1) +
   theme_bw() +
  theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 20),
    axis.title = element_text(size = 20),  # Increase font size of axis titles
    axis.text = element_text(size = 20),   # Increase font size of axis labels
    plot.title = element_text(size = 24, face = "bold"),  # Increase font size of title
    plot.subtitle = element_text(size = 24, face = "italic")  # Increase font size of subtitle
  )
ggsave("bean_emergence_weed_control_location_kgha.png", width = 24, height = 8, dpi = 300)
```