---
title: "bean biomass"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# **Load libraries**
```{r message=FALSE, warning=FALSE}
#Set work directory
setwd("/Users/ey239/Github/Mowtivation/rmarkdowns")

#Load packages 
library(tidyverse) ##install.packages("tidyverse")
library(knitr)
library(patchwork) ##install.packages("patchwork")
library(skimr)     ##install.packages("skimr")
library(readxl)
library(janitor) ##install.packages("janitor")

library(kableExtra) ##install.packages("kableExtra")
library(webshot) ##install.packages("webshot")
webshot::install_phantomjs()
library(viridis) ##install.packages("viridis")
library(lme4) ##install.packages("lme4")
library(lmerTest) ##install.packages("lmerTest")
library(emmeans) ##install.packages("emmeans")
library(rstatix) ##install.packages("rstatix")
#library(Matrix) ##install.packages("Matrix")
library(multcomp) ##install.packages("multcomp")
library(multcompView) ##install.packages("multcompView")
library(ggResidpanel) ##install.packages("ggResidpanel")
#library(car)
#library(TMB)  ##install.packages("TMB")
#library(glmmTMB)  ##install.packages("glmmTMB")
#library(DHARMa)  ##install.packages("DHARMa")

#Load Functions
MeanPlusSe<-function(x) mean(x)+plotrix::std.error(x)

find_logw0=function(x){c=trunc(log(min(x[x>0],na.rm=T)))
d=exp(c)
return(d)}
```
<br>

# **Load and Clean Data**

### **Load individual datasets**

``` {r}
cu_raw_2023 <- read_excel("~/Github/Mowtivation/raw-data/cornell_raw_2023.xlsx")
kable(head(cu_raw_2023))

```

```{r}


#Standardaze column names, convert to factors, check for outliers of variable**
clean_2023 <- clean_names(cu_raw_2023) |>  
  rename ('cultivation'= trt) |> 
  mutate(across(c(cultivation, block, pllot, loc), as.factor)) #|> 
  #mutate(is_outlier = bbm < (quantile(bbm, 0.25) - 1.5 * IQR(bbm)) |
                       #bbm > (quantile(bbm, 0.75) + 1.5 * IQR(bbm)))

#select and convert data for wbm analysis
  
bbm_clean_2023 <-clean_2023 |>              
  
  mutate(bbm_grams_meter = (bbm * 2)) |> 
  mutate(bbm_kg_ha = ((bbm/0.5) *(10000))/(1000)) |>
  mutate(bbm_lbs_ac = (((bbm/0.5) *(10000))/(1000))* 0.892179)
kable(head(bbm_clean_2023)) 
```

# **Model Testing**

### #
#Block is Fixed, 
#Block was included in all models as a fixed factor because blocks were used to control the different field conditions across sections, and thus to reduce variance between eu's
```{r}
#Block is fixed
bbm_fixed <- lm(bbm_kg_ha  ~ cultivation + block  , data = bbm_clean_2023)

resid_panel(bbm_fixed)

#Block is Random
bbm_ran <- lmer(bbm_kg_ha  ~ cultivation + (1|block)  , data = bbm_clean_2023)

resid_panel(bbm_ran)
```

##**Joint test**

```{r}
bbm_fixed |> 
  joint_tests() |> 
  kable()  
```

Interrow cultivation has no impact on weed biomass
