---
title: "Bean Yield"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Load libraries**


```{r message=FALSE, warning=FALSE}
#Set work directory
setwd("/Users/ey239/Github/Mowtivation/rmarkdowns")

#Load packages 
library(tidyverse) ##install.packages("tidyverse")
library(knitr)
library(patchwork) ##install.packages("patchwork")
library(skimr)     ##install.packages("skimr")
library(readxl)
library(janitor) ##install.packages("janitor")
library(kableExtra) ##install.packages("kableExtra")
library(webshot) ##install.packages("webshot")
webshot::install_phantomjs()
library(viridis) ##install.packages("viridis")
library(lme4) ##install.packages("lme4")
library(lmerTest) ##install.packages("lmerTest")
library(emmeans) ##install.packages("emmeans")
library(rstatix) ##install.packages("rstatix")
#library(Matrix) ##install.packages("Matrix")
library(multcomp) ##install.packages("multcomp")
library(multcompView) ##install.packages("multcompView")
library(ggResidpanel) ##install.packages("ggResidpanel")
#library(car)
#library(TMB)  ##install.packages("TMB")
#library(glmmTMB)  ##install.packages("glmmTMB")
#library(DHARMa)  ##install.packages("DHARMa")

#Load Functions
MeanPlusSe<-function(x) mean(x)+plotrix::std.error(x)

find_logw0=function(x){c=trunc(log(min(x[x>0],na.rm=T)))
d=exp(c)
return(d)}
```

<br>

# **Load and Clean Data**

### **Load individual datasets**

``` {r}
cu_raw_all <- read_excel("~/Github/Mowtivation/raw-data/cornell_raw_all.xlsx")
kable(head(cu_raw_all))

```
str(clean_all$beanyd)


```{r}


#Standardaze column names, convert to factors, check for outliers of variable**
clean_all <- clean_names(cu_raw_all) |>  
  rename ('cultivation'= trt) |> 
  mutate(across(c(cultivation, block, pllot, loc, year), as.factor)) #|> 
  #mutate(is_outlier = totwbm < (quantile(totwbm, 0.25) - 1.5 * IQR(totwbm)) |
                       #wbm > (quantile(totwbm, 0.75) + 1.5 * IQR(totwbm)))

#select and convert data for wbm analysis
  beanyd_clean_all <- clean_all |>  
  mutate(beanyd = as.numeric(beanyd)) |>  # Convert beanyd to numeric
  filter(!is.na(beanyd)) |>  # Exclude rows with NA in beanyd
  mutate(
    beanyd_adj_bu_acre = (((beanyd / 454) / (16.4 / 43560)) / 60) * ((100 - 0.00001) / (100 - 14)),
    beanyd_adj_lbs_acre = ((beanyd / 454) / (16.4 / 43560)) * ((100 - 0.00001) / (100 - 14)),
    beanyd_adj_kg_ha = ((beanyd / 454) / (16.4 / 43560)) * 1.12085 * ((100 - 0.00001) / (100 - 14))
  )
kable(head(beanyd_clean_all)) 
```
<br>


## **Model testing**

### **block is fixed**
```{r}
beanyd_fixed <- lmer(beanyd_adj_kg_ha ~ loc*year* cultivation + block 
                     +(1 | year/loc), data = beanyd_clean_all)

resid_panel(beanyd_fixed)
```

### **block is random**
```{r}
beanyd_ran <- lmer(beanyd_adj_kg_ha  ~ cultivation + (1|block)  , data = beanyd_clean_2023)

resid_panel(beanyd_ran)
```

<br>

##**Joint test**
```{r}
 beanyd_fixed |> 
  joint_tests() |> 
  kable()  
```

<br>

# **Means comparison**
```{r message=FALSE}
beanyd_means_all <- 
 emmeans(beanyd_fixed, ~  cultivation)
# Optional: Adjust for multiple comparisons (e.g., using Tukey's method)

pairwise_comparisons<- pairs(beanyd_means_all) 
kable(head(pairwise_comparisons))
```

### **Fisher's method for comparing means**

```{r}
#mowing
cld_cultivation_fisher <-cld(emmeans(beanyd_fixed, ~  cultivation, type = "response"), Letters = letters, sort = TRUE, adjust="none", reversed=TRUE)
cld_cultivation_fisher
```
# **FIGURES**

## **Cultivation**

```{r message=FALSE}
beanyd_clean_all |> 
  left_join(cld_cultivation_fisher) |> 
  ggplot(aes(x = cultivation, y = beanyd_adj_kg_ha, fill = cultivation)) +
  stat_summary(geom = "bar", fun = "mean", width = 0.7) +
  stat_summary(geom = "errorbar", fun.data = "mean_se", width = 0.2) +
  #stat_summary(geom="text", fun = "MeanPlusSe", aes(label= trimws(.group)),size=6.5,vjust=-0.5) +
  labs(
    x = "Interrow weed control method",
    y = expression("Soybean yield" ~ (kg ~ ha^{-1})),
    title = str_c("The influence of interrow weed control method on soybean yield pooled"),
    subtitle = expression(italic("Not signficant"))) +
  
  scale_x_discrete(labels = c("Rolled,\nhigh-residue\ncultivation",
                              "Rolled,\ninterrow\nmowing",
                              "Rolled,\nno additional\nweed control",
                          "Tilled,\nstandard\ncultivation",
                              "Tilled,\ninterrow\nmowing")) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.3))) +
  scale_fill_viridis(discrete = TRUE, option = "D", direction = -1, end = 0.9, begin = 0.1) +
   theme_bw() +
  theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 12)
  )
ggsave("beanydall_plot_cutivation.png", width = 8, height = 6, dpi = 300)
```